stages:
  - build_deploy_test

build_deploy_test:
  stage: build_deploy_test
  script:
    - sudo rsync -qaH --delete ./ /usr/local/src/
    - cd /usr/local/src
    - sudo chown -R root:root .
    - sudo mkdir -p /etc/haproxy
    - sudo rm -rf /var/www/html/test_file
    - sudo ./prep-source
    - sudo ./install-haproxy-service git-haproxy-2.7
    - sudo cp ./ci-haproxy-cfg.txt /etc/haproxy/haproxy.cfg
    - sudo cp -a selfsigned.pem /etc/ssl/certs/local/.
    - sudo ./fullstack
    - sudo touch /var/www/html/test_file
    - sudo docker run --rm ymuski/curl-http3 curl -v -s -f -k https://host.docker.internal/test_file --http3
