stages:
  - build_and_test

build_and_test:
  stage: build_and_test
  script:
    - env > /tmp/cienv.txt
    - sudo -E rsync -qaH --delete ./ /usr/local/src/
    - cd /usr/local/src
    - sudo -E chown -R root:root .
    - sudo -E mkdir -p /etc/haproxy
    - sudo -E rm -rf /var/www/html/test_file
    - sudo -E ./prep-source
    - sudo -E ./install-haproxy-service git-haproxy-2.7
    - sudo -E cp ./ci-haproxy-cfg.txt /etc/haproxy/haproxy.cfg
    - sudo -E cp -a selfsigned.pem /etc/ssl/certs/local/.
    - sudo -E ./fullstack
    - sudo -E rm -rf /tmp/test_file
    - echo "TEST FILE CONTENTS token ${CI_RUNNER_SHORT_TOKEN}" > /tmp/test_file
    - sudo -E cp -f /tmp/test_file /var/www/html/.
    - sudo -E docker run --add-host=host.docker.internal:host-gateway --rm ymuski/curl-http3 curl -v -m 5 -s -f -k "https://host.docker.internal/test_file" --http3
    - echo "TEST FILE CONTENTS token ${CI_RUNNER_SHORT_TOKEN}"
