stages:
  - build_and_test

build_and_test:
  stage: build_and_test
  script:
    - sudo rsync -qaH --delete ./ /usr/local/src/
    - cd /usr/local/src
    - sudo chown -R root:root .
    - sudo mkdir -p /etc/haproxy
    - sudo rm -rf /var/www/html/test_file
    - sudo ./prep-source
    - sudo ./install-haproxy-service git-haproxy-2.7
    - sudo cp ./ci-haproxy-cfg.txt /etc/haproxy/haproxy.cfg
    - sudo cp -a selfsigned.pem /etc/ssl/certs/local/.
    - sudo ./fullstack
    - sudo rm -rf /tmp/test_file
    - echo "TEST FILE CONTENTS" > /tmp/test_file
    - sudo cp -f /tmp/test_file /var/www/html/.
    - sudo docker run --add-host=host.docker.internal:host-gateway --rm ymuski/curl-http3 curl -m 4 -s -f -k "https://host.docker.internal/test_file" --http3
