stages:
  - build_deploy_test

build_deploy_test:
  stage: build_deploy_test
  script:
    - sudo rsync -avH --delete ./ /usr/local/src/ --exclude=git-* --exclude=old.git-*
    - cd /usr/local/src
    - sudo chown -R root:root .
    - sudo mkdir -p /etc/haproxy
    - sudo rm -rf /var/www/html/test_file
    - sudo ./prep-source
    - sudo ./install-haproxy-service git-haproxy-2.7
    - sudo cp ./ci-haproxy-cfg.txt /etc/haproxy/haproxy.cfg
    - sudo ./fullstack
    - sudo touch /var/www/html/test_file
    - curl -s -f http://localhost/test_file
