#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd -P)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/common-functions.sh"

cd "${SCRIPT_DIR}" || die "Can't cd to ${SCRIPT_DIR}"

RET="0"

while [ "$#" -gt 0 ]; do
  REPO_DIR="$1"
  shift
  if [ -z "$REPO_DIR" ]; then
    continue
  else
    cd "${REPO_DIR}" || die "Can't cd to ${REPO_DIR}"
  fi

  # Fetch updates from the remote repository
  git fetch

  CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

  # Get the hash of the current branch in the local repository
  LOCAL_HASH="$(git rev-parse HEAD)"

  # Get the hash of the current branch in the remote repository
  REMOTE_HASH="$(git rev-parse "origin/${CURRENT_BRANCH}")"

  # Check if the local and remote hashes are different
  if [ "${LOCAL_HASH}" != "${REMOTE_HASH}" ]; then
    RET=$((RET+1))
  fi

  cd ..
done

exit "${RET}"
