#!/bin/bash

echo "Starting fullstack script"
echo "CI branch: ${CI_COMMIT_REF_NAME}"
if [ -z "${CI_COMMIT_REF_NAME}" ]; then
  echo "NOT doing CI."
  if [[ "$(hostname -f)" == *"elyograg"* ]]; then
    echo "Full hostname contains elyograg."
    if [[ "$(hostname)" != *"smeagol"* ]]; then
      echo "Hostname does not contain smeagol."
      ./sync_from_smeagol
    fi
  fi
  sudo git pull --rebase
fi

./new-quic git-quictls
./new-haproxy git-haproxy-2.7
