#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname $0)";pwd -P)"
source "${SCRIPT_DIR}/functions.sh"

info "Starting fullstack script"
info "CI branch: ${CI_COMMIT_REF_NAME}"
if [ -z "${CI_COMMIT_REF_NAME}" ]; then
  echo "NOT doing CI."
  if [[ "$(hostname -f)" == *"elyograg"* ]]; then
    info "Full hostname contains elyograg."
    if [[ "$(hostname)" != *"smeagol"* ]]; then
      warn "Syncing from smeagol"
      ./sync_from_smeagol 2>&1
    fi
  fi
  sudo -E git pull --rebase 2>&1
fi

./new-quic git-quictls 2>&1
./new-haproxy git-haproxy-master 2>&1
