#!/bin/sh

err() {
  echo "E: $*" >>/dev/stderr
}

DIR=`dirname $0`/$1/admin/systemd
if [ -e "$DIR" ]; then
  if [ -d "$DIR" ]; then
    cd ${DIR}
    sudo make haproxy.service
    sudo cp haproxy.service /etc/systemd/system/.
    sudo systemctl daemon-reload
    sudo systemctl enable haproxy
    sudo systemctl restart haproxy
  else
    err "location ($DIR) is not a directory."
  fi
else
  err "location ($DIR) does not exist."
fi
