#!/bin/bash

err() {
  echo "E: $*" >>/dev/stderr
}

DIR=`dirname $0`/$1/admin/systemd
if [ -e "$DIR" ]; then
  if [ -d "$DIR" ]; then
    cd ${DIR}
    sudo -E make clean haproxy.service
    sudo -E cp haproxy.service /etc/systemd/system/.
    sudo -E systemctl daemon-reload
    sudo -E systemctl enable haproxy
  else
    err "location ($DIR) is not a directory."
  fi
else
  err "location ($DIR) does not exist."
fi
