#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "$0")" || { echo "Can't CD to $0 ... this should not happen." ; exit 1 ; } ; pwd -P)"
# shellcheck source=/dev/null
source "${SCRIPT_DIR}/functions.sh"
QUICTLS_SRC_DIR="${SCRIPT_DIR}/$1"
MAKE_COUNT="$(make_cpu_count)"

add_bin_to_path() {
  if [ -d /opt/quictls/lib64 ]; then
    QUICTLS_LIB=/opt/quictls/lib64
  else
    QUICTLS_LIB=/opt/quictls/lib
  fi
  rm -f /usr/local/bin/qssl
  cat << EOF > /usr/local/bin/qssl
#!/bin/sh
LD_LIBRARY_PATH=${QUICTLS_LIB}
export LD_LIBRARY_PATH
/opt/quictls/bin/openssl \$*
EOF
  chmod +x /usr/local/bin/qssl
}

#CONFARGS="--prefix=/opt/quictls enable-tls1_3 enable-ktls enable-fips no-idea no-mdc2 no-rc5 no-zlib no-ssl3 enable-unit-test no-ssl3-method enable-rfc3779 enable-cms no-capieng threads"
CONFARGS="--prefix=/opt/quictls enable-tls1_3 no-idea no-mdc2 no-rc5 no-zlib no-ssl3 enable-unit-test no-ssl3-method enable-rfc3779 enable-cms no-capieng threads"

if [ "$(uname -i)" == "x86_64" ]; then
  CONFARGS="${CONFARGS} enable-ec_nistp_64_gcc_128"
fi

if [ -z "$1" ]; then
  die "Command needs an argument, the subdirectory with quictls source"
fi

if [ -e "${QUICTLS_SRC_DIR}" ]; then
  if [ -d "${QUICTLS_SRC_DIR}" ]; then
    cd "${QUICTLS_SRC_DIR}" || die "Unable to cd to ${QUICTLS_SRC_DIR}"
    info "Updating quictls repo"
    sudo -E git pull --rebase 2>&1
    #sudo -E git checkout "$(sudo -E git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)"
    NEW_BRANCH="$(sudo -E git remote show origin | grep -Ew "OpenSSL_1.*quic" | tail -n1 | awk '{print $1}')"
    info "Changing branch to '${NEW_BRANCH}'"
    sudo -E git checkout "${NEW_BRANCH}" 2>&1
    info "Updating quictls repo"
    sudo -E git pull --rebase 2>&1
    info "Cleaning quictls repo"
    sudo -E make -s distclean
    info "Configuring quictls"
    sudo -E ./config "${CONFARGS}"
    RETVAL="$?"
    if [ "$RETVAL" -eq 0 ]; then
      info "Building quictls, may take a few minutes"
      info "Using ${MAKE_COUNT} threads with make"
      sudo -E make -s -j "${MAKE_COUNT}"
      RETVAL="$?"
      if [ "$RETVAL" -eq 0 ]; then
        sudo -E rm -rf /opt/old.quictls
        sudo -E mv /opt/quictls /opt/old.quictls
        info "Installing quictls"
        sudo -E make -s install_sw install_ssldirs
        RETVAL="$?"
        if [ "$RETVAL" -eq 0 ]; then
          sudo -E bash -c "$(declare -f add_bin_to_path); add_bin_to_path"
          sudo -E rm -rf /opt/quictls/ssl/certs
          sudo -E ln -s /etc/ssl/certs /opt/quictls/ssl/certs
          sudo -E make -s distclean
        else
          die "Install failed!"
        fi
      else
        die "Build failed!"
      fi
    else
      die "Configure failed!"
    fi
  else
    die "location (${QUICTLS_SRC_DIR}) is not a directory."
  fi
else
  die "location (${QUICTLS_SRC_DIR}) does not exist."
fi
