#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname $0)";pwd -P)"
QUICTLS_SRC_DIR="${SCRIPT_DIR}/$1"
source "${SCRIPT_DIR}/functions.sh"

CPU_COUNT=$(cpu_count)
((MAKE_COUNT=CPU_COUNT/4))
if [ "${MAKE_COUNT}" -lt 2 ]; then
  MAKE_COUNT=2
fi

add_bin_to_path() {
  if [ -d /opt/quictls/lib64 ]; then
    QUICTLS_LIB=/opt/quictls/lib64
  else
    QUICTLS_LIB=/opt/quictls/lib
  fi
  rm -f /usr/local/bin/qssl
  cat << EOF > /usr/local/bin/qssl
#!/bin/sh
export LD_LIBRARY_PATH=${QUICTLS_LIB}
/opt/quictls/bin/openssl \$*
EOF
  chmod +x /usr/local/bin/qssl
}

do_git_update() {
  git pull --rebase
  git checkout "$(git remote show origin | grep "OpenSSL_1.*quic" | tail -n1 | awk '{print $1}')"
  git pull --rebase
}

#CONFARGS="--prefix=/opt/quictls enable-tls1_3 enable-ktls enable-fips no-idea no-mdc2 no-rc5 no-zlib no-ssl3 enable-unit-test no-ssl3-method enable-rfc3779 enable-cms no-capieng threads"
CONFARGS="--prefix=/opt/quictls enable-tls1_3 no-idea no-mdc2 no-rc5 no-zlib no-ssl3 enable-unit-test no-ssl3-method enable-rfc3779 enable-cms no-capieng threads"

if [ "$(uname -i)" == "x86_64" ]; then
  CONFARGS="${CONFARGS} enable-ec_nistp_64_gcc_128"
fi

if [ -z "$1" ]; then
  die "Command needs an argument, the subdirectory with quictls source"
fi

if [ -e "${QUICTLS_SRC_DIR}" ]; then
  if [ -d "${QUICTLS_SRC_DIR}" ]; then
    cd ${QUICTLS_SRC_DIR} || die "Unable to cd to ${QUICTLS_SRC_DIR}"
    info "Doing git update"
    sudo bash -c "$(declare -f do_git_update); do_git_update"
    info "Cleaning the repo"
    sudo make -s distclean > /dev/null
    info "Configuring the repo"
    sudo ./config ${CONFARGS}
    RETVAL="$?"
    if [ "$RETVAL" -eq 0 ]; then
      info "Building"
      sudo make -s -j ${MAKE_COUNT} > /dev/null
      RETVAL="$?"
      if [ "$RETVAL" -eq 0 ]; then
        sudo rm -rf /opt/old.quictls
        sudo mv /opt/quictls /opt/old.quictls
        info "Installing"
        sudo make -s install_sw install_ssldirs > /dev/null
        RETVAL="$?"
        if [ "$RETVAL" -eq 0 ]; then
          sudo bash -c "$(declare -f add_bin_to_path); add_bin_to_path"
          sudo rm -rf /opt/quictls/ssl/certs
          sudo ln -s /etc/ssl/certs /opt/quictls/ssl/certs
          sudo make -s distclean > /dev/null
        else
          die "Install failed!"
        fi
      else
        die "Build failed!"
      fi
    else
      die "Configure failed!"
    fi
  else
    die "location (${QUICTLS_SRC_DIR}) is not a directory."
  fi
else
  die "location (${QUICTLS_SRC_DIR}) does not exist."
fi
