#!/bin/sh

SCRIPT_DIR="$(cd "$(dirname $0)";pwd -P)"
cd "${SCRIPT_DIR}" || exit 1

if [ -f /etc/redhat-release ]; then
  echo "Trying redhat commands"
  sudo -E yum -y makecache
  sudo -E yum -y install \
    perl-IPC-Cmd \
    perl-Digest-SHA \
    openssl-devel \
    zlib-devel \
    pcre2-devel \
    systemd-devel \
    autoconf \
    automake \
    binutils \
    bison \
    flex \
    gcc \
    gcc-c++ \
    gettext \
    libtool \
    make \
    patch \
    pkgconfig \
    redhat-rpm-config \
    rpm-build \
    rpm-sign \
    byacc \
    cscope \
    ctags \
    diffstat \
    doxygen \
    elfutils \
    gcc-gfortran \
    git \
    indent \
    intltool \
    patchutils \
    rcs \
    subversion \
    swig \
    systemtap \

  # blank line above is intentional
else
  echo "Trying debian/ubuntu commands"
  sudo -E /bin/cp -a /etc/apt/sources.list /etc/apt/sources.list.before
  sudo -E /bin/sed -i "s/^#.*deb-src/deb-src/g" /etc/apt/sources.list
  sudo -E /usr/bin/apt -y update
  sudo -E /usr/bin/apt -y build-dep haproxy
  sudo -E /usr/bin/apt -y build-dep openssl
  sudo -E /usr/bin/apt -y install build-essential git zlib1g-dev
fi

sudo -E rm -rf old.git-haproxy-2.7 > /dev/null
sudo -E mv git-haproxy-2.7 old.git-haproxy-2.7
sudo -E git clone https://git.haproxy.org/git/haproxy-2.7.git git-haproxy-2.7

sudo -E rm -rf old.git-quictls > /dev/null
sudo -E mv git-quictls old.git-quictls
sudo -E git clone https://github.com/quictls/openssl.git git-quictls
