#!/bin/bash

#HAPROXY_OVERRIDE=git-haproxy-2.8
#QUICTLS_OVERRIDE=git-quictls-master

#if [ -z "${NEW_QUIC_BRANCH}" ]; then
#  NEW_QUIC_BRANCH="openssl-3.1.2+quic"
#fi
#export NEW_QUIC_BRANCH
#export MAKE_COUNT
