#!/bin/bash

##HAPROXY_OVERRIDE=git-haproxy-master
#QUICTLS_OVERRIDE=git-quictls-master

if [ -z "${NEW_QUIC_BRANCH}" ]; then
  NEW_QUIC_BRANCH="openssl-3.1.0+quic+locks"
fi
export NEW_QUIC_BRANCH
export MAKE_COUNT
