#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "$0")" || exit ; pwd -P)"
# shellcheck source=/dev/null
source "${SCRIPT_DIR}/functions.sh"

REM_HOST="$1"
if [ -z "$REM_HOST" ]; then
  REM_HOST=smeagol.elyograg.org
fi

sudo -E rsync -avcHP --delete $REM_HOST:/usr/local/src/ /usr/local/src/
